### ISSUE TITLE
Add https support

### ISSUE THREAD

**Issue by pabloab** [janosgyerik/bashoneliners#10]
Right now trying to access the site trough https leads to a self-signed certificate to sni.dreamhost.com. With [Let's Encrypt](https://letsencrypt.org) is really easy, like [commandlinefu.com](https://www.commandlinefu.com/) does.

**Comment by janosgyerik** [comment]
This is fixed. Indeed it was very easy. It was also necessary to fix login with Google. Thanks again for reporting!
