### ISSUE TITLE
Login not working with neither Google nor GitHub

### ISSUE THREAD

**Issue by pabloab** [janosgyerik/bashoneliners#11]
With Google: 

> Error 400: invalid_request

immediately from Google.

With GitHub 

> Internal Server Error
> Ouch! This is our fault :-/

From bashonliners, after giving rights on GitHub.

**Comment by janosgyerik** [comment]
Thanks for reporting. Fixed the login with Google. I'll try to fix GitHub soon. And then the others too.

**Comment by janosgyerik** [comment]
Fixed login with GitHub. For the remaining login issues, created #14 and #15
Thanks again for reporting!
