### ISSUE TITLE
Wheres the rss feed? 

### ISSUE THREAD

**Issue by zDEFz** [janosgyerik/bashoneliners#16]
Tried finding it, but to no avail.

**Comment by port19x** [comment]
Same, any update?

**Comment by zDEFz** [comment]
> Same, any update?

No

**Comment by janosgyerik** [comment]
Here you go: https://www.bashoneliners.com/oneliners/feeds/

Also added a link to it in the top navigation bar, temporarily. Longer term I will move that link to the footer. Later.

Closing this now, but you're feedback is welcome, feel free to reopen if you see issues!
