### ISSUE TITLE
Search Is Broken

### ISSUE THREAD

**Issue by T31337** [janosgyerik/bashoneliners#5]
When I Try To Use The Search Box It Gives Internal Server Error:

#######################ERROR AS FOLLOWS#############################
Ouch! That... really... HURT!

Whatever you were trying to do, it failed, and most probably it is *our* fault, NOT yours.

We want to know about this problem, and for that we need a little help from you.

Please create an issue on GitHub, explaining what happened.

Can you reproduce the problem anytime? Does it happen only sometimes or always?

If GitHub is inconvenient for you, then please email us here instead: bashoneliners@googlegroups.com

**Comment by janosgyerik** [comment]
Thanks for reporting! It's fixed now, please try again.
