### ISSUE TITLE
Error 500 when post a one-liner

### ISSUE THREAD

**Issue by andre487** [janosgyerik/bashoneliners#9]
Try to post one-liner. Then got this:

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@bashoneliners.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

Error 500. 2021-04-18 20:25 UTC

**Comment by janosgyerik** [comment]
Sorry for the very late response. I have an idea why this happened, but I don't have old enough logs to investigate. Sorry about that! Closing this for now.

If you (or anybody else) experience this again, please reopen, and share with me the content of the post:

- summary
- the one-liner
- explanation
- limitations
